[project]
name = "task-flask-app"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Jovial Joe Jayarson", email = "38415384+yozachar@users.noreply.github.com"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
